[package]

name = "bansuri"
version = "0.0.1"
authors = [ "Rajaram <zimbabao@gmail.com>"]

edition = "2018"

[dependencies]

getopts = "0.2"
nom = "3.2.0"

[lib]
name = "bansuri"
path = "src/lib.rs"

[[bin]]
name = "bansuri"
path = "src/main.rs"
